### ISSUE TITLE
CI: Problem with `gen_cli.py`

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#1090]
see: https://app.circleci.com/pipelines/github/mne-tools/mne-bids/4785/workflows/21ad6804-1cc2-42dd-9133-f24de2ea3db5/jobs/6923

```
Traceback (most recent call last):
  File "/home/circleci/mne_bids_env/lib/python3.9/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/circleci/project/doc/sphinxext/gen_cli.py", line 84, in generate_cli_rst
    output[0], output[2] = output[2], output[0]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/mne_bids_env/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/circleci/mne_bids_env/lib/python3.9/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/home/circleci/mne_bids_env/lib/python3.9/site-packages/sphinx/application.py", line 335, in _init_builder
    self.events.emit('builder-inited')
  File "/home/circleci/mne_bids_env/lib/python3.9/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_cli_rst at 0x7fe9bf90c160> for event 'builder-inited' threw an exception (exception: list index out of range)
```

https://github.com/mne-tools/mne-bids/blob/46b0a5300ed5c17ca93b8bbf1d9542069597ef62/doc/sphinxext/gen_cli.py#L1

**Comment by sappelhoff** [comment]
I tested this locally and it only starts failing when updating to MNE dev version.

**Comment by sappelhoff** [comment]
Ahh, could this be related to https://github.com/mne-tools/mne-python/pull/11266 ?

**Comment by sappelhoff** [comment]
@larsoner I think it may fail here because of the removed `print(output)` in `run_subprocess` from https://github.com/mne-tools/mne-python/pull/11266

Do you have a suggestion on what to fix here?
