### ISSUE TITLE
ImportError: cannot import name 'read_montage' from 'mne.channels'

### ISSUE THREAD

**Issue by zuxfoucault** [mne-tools/mne-bids#324]
#### Describe the bug
With mne-python [7410696b8], encountered following error message when I run `python tests/test_write.py`
```
Traceback (most recent call last):
  File "test_write.py", line 32, in <module>
    from mne_bids import (write_raw_bids, read_raw_bids, make_bids_basename,
  File "/home/foucault/anaconda3/envs/mne_bids/lib/python3.7/site-packages/mne_bids/__init__.py", line 6, in <module>
    from mne_bids.write import (write_raw_bids, make_bids_folders, make_bids_basename,  # noqa: E501 F401
  File "/home/foucault/anaconda3/envs/mne_bids/lib/python3.7/site-packages/mne_bids/write.py", line 28,
in <module>
    from mne_bids.utils import (_write_json, _write_tsv, _read_events, _mkdir_p,
  File "/home/foucault/anaconda3/envs/mne_bids/lib/python3.7/site-packages/mne_bids/utils.py", line 24,
in <module>
    from mne.channels import read_montage
ImportError: cannot import name 'read_montage' from 'mne.channels' (/home/foucault/anaconda3/envs/mne_bids/lib/python3.7/site-packages/mne/channels/__init__.py)
```

**Comment by agramfort** [comment]
read_montage has been renamed read_custom_montage

>

**Comment by zuxfoucault** [comment]
Just noticed that the current master has `from mne.channels import make_standard_montage`
The issue should be fixed in the current master.

**Comment by agramfort** [comment]
please close then

>
