### ISSUE TITLE
[BUG] Empty dig and line_freq cause errors

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-bids#503]
```
import os
import os.path as op
import numpy as np

import mne
import mne_bids
from mne.utils import _TempDir

info = mne.create_info(['ch1', 'ch2', 'ch3'], 512,
                       ['seeg'] * 3)
raw_tmp = \
    mne.io.RawArray(np.random.random((3, 1000)) * 1e-6,
                    info)
raw_tmp.info['dig'] = []  # solves issue: raw_tmp.info['dig'] = None
# solves other issue: raw_tmp.info['line_freq'] = 60
out_dir = _TempDir()
raw_tmp.save(op.join(out_dir, 'test.fif'))

raw = mne.io.read_raw_fif(op.join(out_dir, 'test.fif'))

mne_bids.write_raw_bids(raw, 'sub-1_task-mytask', op.join(out_dir, 'bids_dir'),
                            verbose=True, overwrite=True)
```

I got an uninformative index error when my `raw.info['dig']` was an empty list: 
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/alexrockhill/software/mne-bids/mne_bids/write.py", line 1175, in write_raw_bids
    raw, kind, overwrite, verbose)
  File "/Users/alexrockhill/software/mne-bids/mne_bids/dig.py", line 304, in _write_dig_bids
    digpoint = raw.info['dig'][0]
IndexError: list index out of range
```

and `PowerLineFrequency` in `bids_dir/sub-1/ieeg/sub-1_task-mytask_ieeg.json` is null which causes a BIDS validator error.

The dig error looks like it might be related to something @adam2392 was working on recently?
Not sure if anyone knows what happened with powerline and how it could possibly be null instead of 'n/a' but I can look into that later.

**Comment by agramfort** [comment]
can you send a quick bug fix?

>
