### ISSUE TITLE
memory issue in circleCI

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#75]
we get this error:

```py
Unexpected failing examples:
/home/circleci/project/examples/convert_ds000117.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/project/examples/convert_ds000117.py", line 39, in <module>
    fetch_faces_data(data_path, repo, subject_ids)
  File "/home/circleci/project/mne_bids/datasets.py", line 38, in fetch_faces_data
    print_destination=True, resume=True, timeout=10.)
  File "<string>", line 2, in _fetch_file
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/site-packages/mne/utils.py", line 729, in verbose
    return function(*args, **kwargs)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/site-packages/mne/utils.py", line 2008, in _fetch_file
    verbose_bool)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/site-packages/mne/utils.py", line 1923, in _get_http
    local_file.write(chunk)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by sappelhoff** [comment]
Actually, this seems to have been a circle ci error? When re-running the build, it exited positively.

**Comment by sappelhoff** [comment]
Could it be related to this warning: `Your current usage represents 741% of your mne-tools Linux plan's limit. Please upgrade in order to ensure no disruption in building.`?

**Comment by jasmainak** [comment]
741% ???! well, my guess would be that the `ds000117` example is fetching really big files. We should crop the files so that they are tiny and upload a copy somewhere to do a demo.

**Comment by sappelhoff** [comment]
> 741% ???! 

Note that this is for mne-tools, so it also involves MNE-Python and all the other repos :-) I think most of the traffic is by MNE-Python

**Comment by sappelhoff** [comment]
@jasmainak will you take care of the ds00017 example? That one's the reason circleci is failing on our master again:

```
Unexpected failing examples:
/home/circleci/project/examples/convert_ds000117.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 398, in _memory_usage
    out = func()
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 386, in __call__
    exec(self.code, self.globals)
  File "/home/circleci/project/examples/convert_ds000117.py", line 39, in <module>
    fetch_faces_data(data_path, repo, subject_ids)
  File "/home/circleci/project/mne_bids/datasets.py", line 41, in fetch_faces_data
    tf.extractall(path=data_path)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/tarfile.py", line 2008, in extractall
    numeric_owner=numeric_owner)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/tarfile.py", line 2050, in extract
    numeric_owner=numeric_owner)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/tarfile.py", line 2120, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/tarfile.py", line 2169, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/circleci/miniconda/envs/mne_bids/lib/python3.6/tarfile.py", line 252, in copyfileobj
    dst.write(buf)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by jasmainak** [comment]
Alright, this one is for me!

**Comment by teonbrooks** [comment]
@jasmainak is this still an issue? if not, could you close?

**Comment by jasmainak** [comment]
yes, we did not fix it yet ...

**Comment by sappelhoff** [comment]
@jasmainak do you have an idea yet how to adjust the ds000117 example to *not* download nearly 8GB of data? I am getting tired of regularly restarting CircleCI due to memory errors :-D

**Comment by teonbrooks** [comment]
maybe we should be using this instead https://github.com/OpenNeuroDatasets/ds000117. it just downloads the skeleton.

**Comment by jasmainak** [comment]
I wish we could do that. My first thought was to use `datalad` as it downloads files on demand instead of getting the full 8 GB zip. However, they have also switched to BIDS format.

We could probably have our own mirror for the data (truncated) of one subject. But maybe we should check if the license allows truncating. Really, we just need the headers for testing and examples ...

**Comment by teonbrooks** [comment]
@jasmainak, so is the data on osf pre-BIDS organized?

**Comment by jasmainak** [comment]
yes. I think there is a plan to move MNE datasets into BIDS format eventually but not yet ...

**Comment by jasmainak** [comment]
closing this as we didn't hit this problem again in 6 months
