### ISSUE TITLE
participants.tsv files are erroneously expected to always have more than one column

### ISSUE THREAD

**Issue by SebastianSpeer** [mne-tools/mne-bids#891]
Dear MNE BIDS team,

I'm trying to read in data via mne-bids. Everything works fine until the channel locations are read in.

This is what my channels tsv file looks like:

![image](https://user-images.githubusercontent.com/29842476/138481381-a7c489fc-29cb-41ad-bcd5-77133093f8db.png)

This is the error message I'm receiving:

```
> ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-77-d54a13bf5b31> in <module>
      4 bids_path = BIDSPath(subject=subject, task ='xxxx',suffix= suffix,
      5                       datatype=datatype, root=bids_root)
----> 6 raw = read_raw_bids(bids_path=bids_path, verbose=False)

~/anaconda3/lib/python3.8/site-packages/mne_bids/read.py in read_raw_bids(bids_path, extra_params, verbose)
    711     subject = f"sub-{bids_path.subject}"
    712     if op.exists(participants_tsv_fpath):
--> 713         raw = _handle_participants_reading(participants_tsv_fpath, raw,
    714                                            subject, verbose=verbose)
    715     else:

~/anaconda3/lib/python3.8/site-packages/mne_bids/read.py in _handle_participants_reading(participants_fname, raw, subject, verbose)
    172 def _handle_participants_reading(participants_fname, raw,
    173                                  subject, verbose=None):
--> 174     participants_tsv = _from_tsv(participants_fname)
    175     subjects = participants_tsv['participant_id']
    176     row_ind = subjects.index(subject)

~/anaconda3/lib/python3.8/site-packages/mne_bids/tsv_handler.py in _from_tsv(fname, dtypes)
    138     data = np.loadtxt(fname, dtype=str, delimiter='\t',
    139                       comments=None, encoding='utf-8-sig')
--> 140     column_names = data[0, :]
    141     info = data[1:, :]
    142     data_dict = OrderedDict()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

```
Could this issue be due to an incorrectly formatted tsv file?

**Comment by skjerns** [comment]
I'm working (presumably) on the same dataset (EEGManyPipelines study), and there is a further error with this .tsv file that is not fixed with simply loading the data with `ndim=2`:

```Python
  File "<decorator-gen-584>", line 24, in make_report

  File "c:\users\simon\anaconda3\lib\site-packages\mne_bids\report.py", line 500, in make_report
    participant_summary = _summarize_participants_tsv(root)

  File "c:\users\simon\anaconda3\lib\site-packages\mne_bids\report.py", line 232, in _summarize_participants_tsv
    n_age_unknown = len(p_ages)

TypeError: object of type 'NoneType' has no len()
```
